### ISSUE TITLE
Over resource limits on Streamlit Cloud

### ISSUE THREAD

**Issue by dbonafilia** [streamlit/demo-deepdream#1]
Hey there :wave: Just wanted to let you know that [your app on Streamlit Cloud deployed from this repo](https://share.streamlit.io/streamlit/demo-deepdream) has gone over its resource limits. Access to the app is temporarily limited. Visit the app to see more details and possible solutions.

**Comment by randyzwitch** [comment]
The demo is back up, thanks for letting us know @dbonafilia!
